name: CI workflow-Run Tests

on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3  # Checkout the repository code
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
